### ISSUE TITLE
Let user select pull/push protocol for buildconf

### ISSUE THREAD

**Issue by maltewi** [ESROCOS/buildconf#11]
## Problem Description
As reported by Miguel:

When you bootstrap the system, it asks for the method to access repositories and this can be set for all packages.

However, it is not possible to select the push/pull methods for the buildconf itself. As you can see below, the buildconf repository is cloned and configured by defult with push to a Git URL.

```
esrocos@esrocos-box:~/esrocos_workspace/autoproj$ git remote show autobuild
* remote autobuild
  Fetch URL: https://github.com/ESROCOS/buildconf.git
  Push  URL: git@github.com:ESROCOS/buildconf.git
  HEAD branch: stable
  Remote branches:
    add_gui_pkgs   new (next fetch will store in remotes/autobuild)
    master         tracked
    singular_aadls tracked
    stable         tracked
  Local branches configured for 'git pull':
    master merges with remote master
    stable merges with remote stable
  Local ref configured for 'git push':
    master pushes to master (up to date)
```

This doesn't work with our firewall. We therefore need to change it manually with:

`git remote set-url --push autobuild https://github.com/ESROCOS/buildconf.git`

Taking into account that autoproj already asks the push/pull method for the package repositories, it would be nice if it would do it also for the buildconf one.

## What's to do
The push/pull URLs for the buildconf come from the `install_esrocos-script`:

pull: https://github.com/ESROCOS/buildconf/blob/f0cf0acad97b6bb26b7bdc3da00cbd07712d2a15/install_esrocos#L3
push: https://github.com/ESROCOS/buildconf/blob/f0cf0acad97b6bb26b7bdc3da00cbd07712d2a15/install_esrocos#L75-L75

We should ask the user about the protocol and assemble the URL similar to https://github.com/ESROCOS/buildconf/blob/f0cf0acad97b6bb26b7bdc3da00cbd07712d2a15/install_esrocos#L77-L87

**Comment by Kynneb** [comment]
As a fix I edited the script that push / pull will use the same protocol - so http can be used for both as well as ssh
