### ISSUE TITLE
Investigate better storage location for CMake and init.rb stuff

### ISSUE THREAD

**Issue by maltewi** [ESROCOS/buildconf#17]
### Suggestion
It should either go to package set or individual repository included via default build layout.

### Rationale
All ESROCOS features should also be available form user-customized buildconfs

**Comment by Kynneb** [comment]
Over the last days I have experimented a bit with that topic. In #18 some files are already moved out of the buildconf into a new package "tools/config".

Candidates to move out of the buildconf would be:

- The init.rb parts exporting / setting environment variables
- cmake_modules (should be installed)
- templates (should be installed)
- cmake_macros (should be installed)

However, I stumbled over multiple problems:

- many other packages would need a explicit dependency to ensure tools/config is always installed first
- Although setting the CMAKE_MODULES_PATH in the init.rb the modules would not be found by the packages 
- the environment variables seemed only to be reliably when set in the autoproj folder (i.e. the buildconf)

So essentially I was  only able to move out the templates and cmake macros functionally but perhaps this is not a problem of principle but only of my autoproj-fu. Next week I might look more into this.

**Comment by maltewi** [comment]
what about moving these things to the package set?

**Comment by Kynneb** [comment]
Update:
- worked out the problem with the cmake modules (was set concurrently at two different points, my bad)
- Many of the variables could also just be set in the cmake file instead of the init.rb (and thus reliably outside of the buildconf) but I am not quite sure if that would be good practice
