### ISSUE TITLE
Release 0.1 due to July 2017

### ISSUE THREAD

**Issue by maltewi** [ESROCOS/buildconf#2]
A first release is planned for PDR. We defined the following functionalites as part of the Release:

 1. Workflow Tools
 2. Types
 3. Tutorial Packages
 4. User Reference - Installation instructions / Tutorial
 5. (PUS Types by GMV)
 6. Release Notes
 7. Repository Tags
 8. Clean up Repository Structure

Following I'll give an overview on the status of individual items. 

- [x] to 1.: Tools are functional.
- [x] to 2.: @Kynneb has cleaned up repositories from old stuff. I wanted to iterate over the type definitions, but didn't manage to do so. I would propose to leave them as they are for this release.
- [ ]  to 3.: Not there, yet. @Kynneb do you think you'll manage to create them?
- [x] to 4.: I've setup a [Github Page (preview)](https://esrocos.github.io/index2) with [installation instructions](https://esrocos.github.io/Installation/) and additional information.
  The template is still quite messed up and additional content is welcome, but I'd say for the first internal release it's okay.
- [x] to 5.: Was optional anyway and since we're all busy and I didn't here from it I'd propose to leave it from the release. @mmunoz-gmv what's your opinion regarding this?
- [ ] to 6.: Still to be done
- [x] to 7.: Still to be done
- [x] to 8.: @Kynneb you still have this on your agenda? With this I mean the renaming of the repos as discussed in our recent meeting,(

**Comment by Kynneb** [comment]
1. Is not complete yet as there are some issues left open with the integration of remote dependencies
3. As my priorities concern 1. that could be hard to achieve this week, but perhaps with a little delay at the end of this month?
@maltewi I suppose 8. = 7.? Still have it on my mind but looked into 1. first as that's my top prio at the moment.

**Comment by Kynneb** [comment]
Update to 1:
Create, fetch dependency and edit are up and working (but not broadly tested). esrocos_publish is not implemented at this point, but I think for the first release the other open issues are more important so I will take care of them first.

**Comment by maltewi** [comment]
> esrocos_publish is not implemented at this point, but I think for the first release the other open issues are more important so I will take care of them first.

Agreed. Leave it away for now.

>  I suppose 8. = 7.? Still have it on my mind but looked into 1. first as that's my top prio at the moment.
Clarified with editing original post (some Markdown cleverness was changing my numbering).

@Kynneb From your point of view, is 1. now finished? If so, I'd suggest to move to 8. first and afterwards to 3.

**Comment by Kynneb** [comment]
Agree

**Comment by Kynneb** [comment]
Update 8: Tidied up quite a bit, did a lot of renaming and git branch cleaning. Tools still worked for me but were not widely tested.

**Comment by Kynneb** [comment]
Update 7: Tagged latest working versions as release 'v0.1 PDR Release'

**Comment by maltewi** [comment]
Close because of https://github.com/ESROCOS/buildconf/issues/2#issuecomment-313055960
