### ISSUE TITLE
CI

### ISSUE THREAD

**Issue by Kynneb** [ESROCOS/buildconf#20]
in #19 I will research the feasability of an automated ESROCOS installation process.

**Comment by Kynneb** [comment]
The good news is: The build runs fine, the bad new is: it needs 1:20h on my system. I will see if we can use the jenkins infrastructure at dfki but perhaps it might make sense to have an own server? 

@maltewi @jhidalgocarrio what do you think?

**Comment by jhidalgocarrio** [comment]
It sounds good to me. 1:20h... it is not that bad, it usually takes longer when the number of packages grow.
IMO when ready: squash and merge to master.

**Comment by Kynneb** [comment]
Ah, sorry. Of course depending on the actual constraints 1:20h is absolutely okay for a whole system installation. But for regular testing it takes quite a bite out of my workday so some external build server which can run over night or for CI on push would be nice ;-)

**Comment by jhidalgocarrio** [comment]
sure :+1:

**Comment by maltewi** [comment]
You have tried a local jenkins installation already or used the internal DFKI server... so that we know it's the technology we want to use?

If yes, we can ask to setup an externally visible server

**Comment by Kynneb** [comment]
I reached out to the admin of the internal dfki server and will investigate if that's a good solution. He set up a config for us or already but I did not get to test it yet.
