### ISSUE TITLE
Issue when installing on vanilla Taste VM

### ISSUE THREAD

**Issue by haianos** [ESROCOS/buildconf#21]
Symptom:
```
Fetching hitimes 1.2.6
Installing hitimes 1.2.6 with native extensions
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    current directory: /home/taste/.autoproj/gems/ruby/2.3.0/gems/hitimes-1.2.6/ext/hitimes/c
/usr/bin/ruby2.3 -r ./siteconf20180327-31981-303d6p.rb extconf.rb
mkmf.rb can't find header files for ruby at /usr/lib/ruby/include/ruby.h

extconf failed, exit code 1

Gem files will remain installed in /home/taste/.autoproj/gems/ruby/2.3.0/gems/hitimes-1.2.6 for inspection.
Results logged to /home/taste/.autoproj/gems/ruby/2.3.0/extensions/x86-linux/2.3.0/hitimes-1.2.6/gem_make.out

An error occurred while installing hitimes (1.2.6), and Bundler cannot continue.
Make sure that `gem install hitimes -v '1.2.6'` succeeds before bundling.

In Gemfile:
  autoproj was resolved to 2.5.1, which depends on
    autobuild was resolved to 1.13.0, which depends on
      tty-prompt was resolved to 0.15.0, which depends on
        timers was resolved to 4.1.2, which depends on
          hitimes
FATAL: failed to install autoproj in /media/sf_esrocos_software/.autoproj
```

Solution:
```
sudo apt-get install ruby2.3-dev 
sudo gem install hitimes -v '1.2.6'

```

**Comment by mfrigerio17** [comment]
After solving the ruby/hitimes issue, after a few steps I get this error

  ERROR: types/base_support, which is selected in the layout, is unknown: cannot resolve types/base_support: types/base_support is not an osdep and it cannot be resolved as a source package

**Comment by Kynneb** [comment]
Hey, which TASTE-Version and which esrocos install script did you use?

**Comment by haianos** [comment]
In my case:
  * TASTE-VM-9.0-32bit
  * the latest on buildconf repo

**Comment by mfrigerio17** [comment]
Kynneb, I tried the install script one gets with the `wget` command in the readme, and had problems.
However, the install script in the 'stable' branch of this repo does not cause the `ERROR: types/base_support` I reported earlier.

I am also using the Taste-VM 9.0

**Comment by Kynneb** [comment]
The solution is indeed to install ruby2.3-dev, as some newer additions require the possibility to add ruby-extensions. I think the most sensible way is to introduce a check into the installation process.
 
please have a look into #22
