### ISSUE TITLE
[Reuse of ESROCOS components] Required and provided interface connections

### ISSUE THREAD

**Issue by Kynneb** [ESROCOS/buildconf#4]
To reuse an ESROCOS component it is assumed that the components files (source and interfaceview) are provided in the ESROCOS workspace.

Within the TASTE gui an external interface-view can be imported and any provided functions included as a predefined pattern. However any data out ports (modelled with RIs) have to be connected to a PI which is specified to match the RI as on connection the RIs naming and parameter definition will be updated to match the PIs which is a bit uncomfortable. 

Perhaps the TASTE-GUI can be adapted in a way to provide the possibility to both let the user define a PI matching a given RI as it is already possible the other way around.

**Comment by maltewi** [comment]
@Kynneb I think the TASTE export functionality already deals partly with this. Right? Can this be closed?
