### ISSUE TITLE
[REUSE OF ESROCOS TYPES] Importing of multiple dataview.aadl files

### ISSUE THREAD

**Issue by Kynneb** [ESROCOS/buildconf#5]
currently it seems that the taste gui is not able to import multiple data views, so that all asn files containing data types for the project have to be compiled into one single monolithic file at the moment.

**Comment by maltewi** [comment]
@Kynneb do the ongoing discussions of reusable components in TASTE deal with this issue? I yes it could be closed here, since the solution is discussed elsewhere.
