### ISSUE TITLE
Tiny error in installation instructions

### ISSUE THREAD

**Issue by AlexanderFabisch** [ESROCOS/buildconf#8]
The installations instructions state that

    A directory "esrocos_workspace" will be created

This is not correct. It should be "~/esrocos_workspace".

**Comment by maltewi** [comment]
Thanks for reporting. Closed with https://github.com/ESROCOS/buildconf/commit/ea7e4fdaa62836e5c9a45d5095534d4748c1a52e and https://github.com/ESROCOS/buildconf/commit/ea7e4fdaa62836e5c9a45d5095534d4748c1a52e
